### PR TITLE
Add rescue command and admin stuff

### PR DESCRIPTION
**Pull request by PatrykPaluch**
Command `/r` or `/rescue` teleports player to last grounded unfreezed position
- This command can be disabled in server settings
- Some maps have places when you can stuck (or all team can stuck), to avoid players frustration server admin can turn on rescue.
- Rescue have delay settings to avoid spamming

Admin stuff (server console - F2):
- `super` makes player unfreezable and gives infinite jump and hook time
- `move` moves player one block in a given direction
- This stuff is good for mappers.

### CODE REVIEW

**Comment by DawidSsS** [comment]
`src/game/gamecore.cpp: In member function ‘void CCharacterCore::Tick(bool)’:
src/game/gamecore.cpp:127:15: error: ‘struct CNetObj_PlayerInput’ has no member named ‘m_Super’
    if(m_Input.m_Super){
               ^
src/game/gamecore.cpp:295:15: error: ‘struct CNetObj_PlayerInput’ has no member named ‘m_Super’
   if(!m_Input.m_Super) m_HookTick++;
               ^`

**Comment by Dune-jr** [comment]
@DawidSsS Yeah, the PR does not build.
This PR modifies gamecore.cpp and thus breaks the nethash, so it's not the right approach either way.
About the error: there is an unused lowercase `m_super`, that might be the source of the error.

**Comment by DawidSsS** [comment]
thx for answer. i just trying to make private server for friends and this would be very helpful (we are not pro) :/

**Comment by Dune-jr** [comment]
I understand. You can add NetObjBool("m_Super") in protocol.h line 77 so it builds. Some issues may remain

**Comment by DawidSsS** [comment]
no it's doesn't help. ok thanks for trying to help. i suck in cpp :P

**Comment by Dune-jr** [comment]
Sorry, network.h. It builds with this patch:

```diff
diff --git a/datasrc/network.py b/datasrc/network.py
index 2320b3dc..3962dc01 100644
--- a/datasrc/network.py
+++ b/datasrc/network.py
@@ -87,6 +87,7 @@ Objects = [
                NetBool("m_Jump"),
                NetIntAny("m_Fire"),
                NetBool("m_Hook"),
+               NetBool("m_Super"),

                NetFlag("m_PlayerFlags", PlayerFlags),
```

**Comment by DawidSsS** [comment]
Yes it helps with one issue but... XD ok leave it if you want 

`[ 50%] Building CXX object CMakeFiles/teeworlds_srv.dir/src/generated/server_data.cpp.o
[ 51%] Linking CXX executable teeworlds_srv
CMakeFiles/teeworlds_srv.dir/src/game/server/entities/character.cpp.o: In function `CCharacter::SetWeapon(int)':
/home/build-ddserver/src/game/server/entities/character.cpp:143: undefined reference to `CmaskRace(CGameContext*, int)'
CMakeFiles/teeworlds_srv.dir/src/game/server/entities/character.cpp.o: In function `CCharacter::FireWeapon()':
/home/build-ddserver/src/game/server/entities/character.cpp:299: undefined reference to `CmaskRace(CGameContext*, int)'
/home/build-ddserver/src/game/server/entities/character.cpp:313: undefined reference to `CmaskRace(CGameContext*, int)'
/home/build-ddserver/src/game/server/entities/character.cpp:362: undefined reference to `CmaskRace(CGameContext*, int)'
/home/build-ddserver/src/game/server/entities/character.cpp:384: undefined reference to `CmaskRace(CGameContext*, int)'
CMakeFiles/teeworlds_srv.dir/src/game/server/entities/character.cpp.o:/home/build-ddserver/src/game/server/entities/character.cpp:396: more undefined references to `CmaskRace(CGameContext*, int)' follow
CMakeFiles/teeworlds_srv.dir/src/game/server/entities/character.cpp.o: In function `CCharacter::OnPhysicsStep(vector2_base<float>, float, void*)':
/home/build-ddserver/src/game/server/entities/character.cpp:904: undefined reference to `CGameControllerRACE::OnPhysicsStep(int, vector2_base<float>, float)'
CMakeFiles/teeworlds_srv.dir/src/game/server/entities/laser.cpp.o: In function `CLaser::DoBounce()':
/home/build-ddserver/src/game/server/entities/laser.cpp:71: undefined reference to `CmaskRace(CGameContext*, int)'
CMakeFiles/teeworlds_srv.dir/src/game/server/entities/projectile.cpp.o: In function `CProjectile::Tick()':
/home/build-ddserver/src/game/server/entities/projectile.cpp:82: undefined reference to `CmaskRace(CGameContext*, int)'
CMakeFiles/teeworlds_srv.dir/src/game/server/gamecontext.cpp.o: In function `CGameContext::CreateDamage(vector2_base<float>, int, vector2_base<float>, int, int, bool)':
/home/build-ddserver/src/game/server/gamecontext.cpp:119: undefined reference to `CmaskRace(CGameContext*, int)'
CMakeFiles/teeworlds_srv.dir/src/game/server/gamecontext.cpp.o: In function `CGameContext::CreateExplosion(vector2_base<float>, int, int, int)':
/home/build-ddserver/src/game/server/gamecontext.cpp:147: undefined reference to `CmaskRace(CGameContext*, int)'
CMakeFiles/teeworlds_srv.dir/src/game/server/gamecontext.cpp.o: In function `CGameContext::CreatePlayerSpawn(vector2_base<float>, int)':
/home/build-ddserver/src/game/server/gamecontext.cpp:176: undefined reference to `CmaskRace(CGameContext*, int)'
CMakeFiles/teeworlds_srv.dir/src/game/server/gamecontext.cpp.o:/home/build-ddserver/src/game/server/gamecontext.cpp:187: more undefined references to `CmaskRace(CGameContext*, int)' follow
CMakeFiles/teeworlds_srv.dir/src/game/server/gamecontext.cpp.o: In function `CGameContext::OnConsoleInit()':
/home/build-ddserver/src/game/server/gamecontext.cpp:1494: undefined reference to `CGameContext::ConTeleport(IConsole::IResult*, void*)'
/home/build-ddserver/src/game/server/gamecontext.cpp:1495: undefined reference to `CGameContext::ConTeleportTo(IConsole::IResult*, void*)'
/home/build-ddserver/src/game/server/gamecontext.cpp:1496: undefined reference to `CGameContext::ConGetPos(IConsole::IResult*, void*)'
/home/build-ddserver/src/game/server/gamecontext.cpp:1498: undefined reference to `CGameContext::ConSuper(IConsole::IResult*, void*)'
/home/build-ddserver/src/game/server/gamecontext.cpp:1499: undefined reference to `CGameContext::ConMove(IConsole::IResult*, void*)'
CMakeFiles/teeworlds_srv.dir/src/game/server/gamecontext.cpp.o: In function `CGameContext::OnInit()':
/home/build-ddserver/src/game/server/gamecontext.cpp:1534: undefined reference to `CGameContext::InitChatConsole()'
/home/build-ddserver/src/game/server/gamecontext.cpp:1539: undefined reference to `CGameContext::LoadMapSettings()'
/home/build-ddserver/src/game/server/gamecontext.cpp:1545: undefined reference to `CGameControllerFC::CGameControllerFC(CGameContext*)'
/home/build-ddserver/src/game/server/gamecontext.cpp:1547: undefined reference to `CGameControllerRACE::CGameControllerRACE(CGameContext*)'
/home/build-ddserver/src/game/server/gamecontext.cpp:1552: undefined reference to `CFileScore::CFileScore(CGameContext*)'
collect2: error: ld returned 1 exit status
CMakeFiles/teeworlds_srv.dir/build.make:457: recipe for target 'teeworlds_srv' failed
make[2]: *** [teeworlds_srv] Error 1
CMakeFiles/Makefile2:375: recipe for target 'CMakeFiles/teeworlds_srv.dir/all' failed
make[1]: *** [CMakeFiles/teeworlds_srv.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by Dune-jr** [comment]
It builds fine for me. Can you build the clean branch without the PR just fine? `git pull https://github.com/Dune-jr/teeworlds.git ddr`

**Comment by DawidSsS** [comment]
Yes clear branch is ok :)

**Comment by Learath2** [comment]
The changes to gamecore we used to tolerate by fixing the nethash, I doubt that's an acceptable solution for you though :)

**Comment by Dune-jr** [comment]
@Learath2 it's fine to fix the nethash by my book, I just don't think they are necessary here (and if they are, the nethash should be fixed).
In fact, there is a client-side nethash hack in 0.7.3 itself, and there were talks of straight-up removing it: https://github.com/teeworlds/teeworlds/pull/2122/files

**Comment by Dune-jr** [comment]
@DawidSsS Can you try building with bam? It works. I think the issue is the CMake configuration here

**Comment by DawidSsS** [comment]
@Dune-jr Thx it works. You are the best :)

**Pull request closed without merging**
